name: persona
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - black
  - cudatoolkit
  - docopt
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pylint
  - pytorch
  - seaborn
  - torchvision
  - tqdm
  - pip:
      - facenet-pytorch
