name: face-recognition
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - black
  - cudatoolkit
  - docopt
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pip
  - pylint
  - pytest
  - pytest-cov
  - pytest-timeout
  - pytest-xdist
  - pytorch
  - seaborn
  - torchvision
  - pip:
      - facenet-pytorch
